global:
  node_env: development

recipesbook-service:
  mongo_proto: mongodb+srv
  mongo_host: cluster0.2n6tvhy.mongodb.net
  mongo_user: YourYummy
  mongo_pwd: KBGnT6WYuSEMFiJK
  mongo_dbname: recipesBook
  image: recipebook:latest