apiVersion: v1
kind: Service
metadata:
  name: recipesBook
  labels:
    {{- include "recipesBook.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app.kubernetes.io/name: recipesBook
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
