version: '2.0'
services:

# ===============================================
  database:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    networks:
      - test
# ===============================================
networks:
  test:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.20.0/28
